spring:
  kafka:
    bootstrap-servers:
      - 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
      group-id: room335
    listener:
      ack-mode: manual_immediate

topic:
  test-string-topic: 'test-topic'
  test-message-topic: 'test-message-topic'
  room-creation: 'room-creation'

