spring:
  kafka:
    bootstrap-servers:
      - 'localhost:9092'
    consumer:
      auto-offset-reset: earliest
      group-id: room335

topic:
  test-topic-name: 'test-topic'
  room-creation: 'room-creation'

